### ISSUE TITLE
Cannot Teleport

### ISSUE THREAD

**Issue by eauxnine** [cinderblocks/radegast#23] opened 2023-01-17 15:11 UTC
Since I updated the viewer, I cannot teleport anywhere on this specific viewer. I get an error of disconnected from grid but the avatar is still online and is able to move around. I tried to downgrade to 2.39 and still have the same issue.

**Comment by cinderblocks** [comment] 2023-01-19 02:23
How are you teleporting? Specific steps that I can reproduce please. I was able to teleport via landmark and map just now.

**Comment by eauxnine** [comment] 2023-01-19 20:44
Alright, once I log in. Someone will offer me a teleport. I’ll accept it and within 2-3 mins of trying to teleport, it’ll announce that I’ve disconnected from the grid. Teleport LMs work 25% of the time. Same if I request one, I’ll attempt to teleport, 2-3 mins will pass. Then disconnected from grid. But I’ll still be online for others for hours even though I’ve disconnected.

**Comment by mutantspore** [comment] 2023-01-19 22:17
I'd like to add a "me too" as I have similar issues to @eauxnine . Won't TP from double click on Map... times out and disconnects. If I remember correctly an offered TP was about the only way I could get about though that was not always successful. 

I'll experiment in more detail and post a more helpful note.

**Comment by JoranJix** [comment] 2023-01-20 10:15
I tried it via offering teleports. Works on a region. Does not work to another region.
llTeleportAgent. Same Problem.
RLV force teleopr. Same issue
Landmarks. Same issue.
I tried it during multiple times of the day to make sure its not the grid itself.

**Comment by cinderblocks** [comment] 2023-01-21 01:06
I've got some time this weekend to work on this. What are some to and from regions in Second Life that are easiest to reproduce this?

**Comment by cinderblocks** [comment] 2023-01-27 17:45
Can someone test with this build and tell me if the problem is resolved? https://ci.appveyor.com/api/buildjobs/65im9tx9ukytn0ad/artifacts/RadegastSetup_x64-3.0.350.msi

**Comment by JoranJix** [comment] 2023-01-27 21:29
I just tried to teleport one of my avatars from "Bon Temp"s to "Quarabia" using the map and the version that was posted. 
The avatar left the map and I got the following message 

"Teleport failed
[22:18] Disconnected: SimShutdown
"
But the avatar is still online. Same for the region
https://gyazo.com/dbde9c550fb36d17fbc82a9809eb305b
Nect region Hahne. An old region by LL.
https://gyazo.com/c7e0e23b90568b9d121ebddb9ad9a233
https://gyazo.com/f0057db9b186be0dd7fe6e0488d8df7a
The result stays the same.
So with Radegast the avatar is stuck.
Radegast seems really broken at this moment.
When trying to reconnect, I can relog the avatar at this state, but the map is not usable anymore. I need to close it and start over.
Same goes for Inventory, Groups, Friends,Media. Voice,3D Scene. The only tabs usable are Chat and Objects.

**Comment by eauxnine** [comment] 2023-01-27 23:55
same as @JoranJix. The issue remains.

**Comment by cinderblocks** [comment] 2023-01-28 03:22
Can I get a log from somebody? Either pasting relevent output here or e-mailed to cinder@cinderblocks.biz? Log can be found at C:\Users\<your computer username>\AppData\Roaming\Radegast\Radegast.log

**Comment by JoranJix** [comment] 2023-01-28 04:00
Interesting. I wanted to send a fresh log. Removed everything. Also removed any version of radegast and did a fresh install with the latest version posted by @cinderblocks . That worked. Now I was able to port one time! Then it just gave me failed TPs.

04:52:52 [WARN] - < >: Failed loading cached avatar names: System.IO.FileNotFoundException: Die Datei "C:\Users\***\AppData\Roaming\Radegast\name.cache" konnte nicht gefunden werden.
Dateiname: "C:\Users\***\AppData\Roaming\Radegast\name.cache"
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   bei Radegast.NameManager.<LoadCachedNames>b__32_0(Object syncx) in C:\projects\radegast\Radegast\Core\NameManager.cs:Zeile 328.

04:52:54 [INFO] - Inworld sound disabled
04:53:12 [DEBUG] - No crash marker file C:\Users\***\AppData\Roaming\Radegast\crash_marker found
04:53:12 [DEBUG] - Successfully created and locked marker file C:\Users\***\AppData\Roaming\Radegast\crash_marker
04:53:12 [INFO] - Reporting normal shutdown of the last application run to the grid login service
04:53:12 [DEBUG] - Marking start of execution run, creating file: C:\Users\***\AppData\Roaming\Radegast\crash_marker
04:53:15 [INFO] - <mooncookieservant Resident>: Connecting to (35.91.208.199:13015)
04:53:17 [DEBUG] - <mooncookieservant Resident>: Reading inventory cache from C:\Users\***\AppData\Roaming\Radegast\mooncookieservant Resident\inventory.cache
04:53:20 [INFO] - <mooncookieservant Resident>: Successfully set appearance
04:53:27 [DEBUG] - <mooncookieservant Resident>: Finished updating inventory folders, saving cache...
04:53:27 [INFO] - Caching 395 inventory items to C:\Users\***\AppData\Roaming\Radegast\mooncookieservant Resident\inventory.cache
04:53:38 [INFO] - <mooncookieservant Resident>: Requesting teleport to region handle 1119302837332480
04:53:38 [DEBUG] - Playing sound at <-48,5,36,8,93,7> ID d7a9a565-a013-2a69-797d-5332baa1a947
04:53:38 [DEBUG] - Playing sound at <-48,5,36,8,93,7> ID d7a9a565-a013-2a69-797d-5332baa1a947
04:53:38 [WARN] - <mooncookieservant Resident>: Failed saving asset to cache (Der Prozess kann nicht auf die Datei "C:\Users\***\AppData\Roaming\Radegast\cache\d\7\d7a9a565-a013-2a69-797d-5332baa1a947" zugreifen, da sie von einem anderen Prozess verwendet wird.)
04:53:38 [INFO] - <mooncookieservant Resident>: Connecting to (35.163.94.119:13037)
04:53:39 [INFO] - <mooncookieservant Resident>: Moved to new sim Hahne (35.163.94.119:13037)
04:54:03 [DEBUG] - Playing sound at <-128,0,8,2,128,0> ID d7a9a565-a013-2a69-797d-5332baa1a947
04:54:03 [DEBUG] - Playing sound at <-128,0,8,2,128,0> ID d7a9a565-a013-2a69-797d-5332baa1a947
04:54:03 [DEBUG] - Playing sound at <-128,0,8,2,128,0> ID d7a9a565-a013-2a69-797d-5332baa1a947
04:54:03 [INFO] - <mooncookieservant Resident>: Moved to new sim Bon Temps (35.91.208.199:13015)
04:54:54 [INFO] - <mooncookieservant Resident>: Caps system for Hahne (35.163.94.119:13037) is aborting
04:56:26 [WARN] - <mooncookieservant Resident>: Could not find region named quarabia
04:56:34 [INFO] - <mooncookieservant Resident>: Requesting teleport to region handle 579442628203264
04:56:42 [INFO] - <mooncookieservant Resident>: Requesting teleport to region handle 1203965232719872
04:56:42 [DEBUG] - Playing sound at <-48,0,36,9,91,0> ID d7a9a565-a013-2a69-797d-5332baa1a947
04:56:42 [DEBUG] - Playing sound at <-48,0,36,9,91,0> ID d7a9a565-a013-2a69-797d-5332baa1a947
04:57:29 [INFO] - Caching 395 inventory items to C:\Users\***\AppData\Roaming\Radegast\mooncookieservant Resident\inventory.cache
04:57:29 [INFO] - <mooncookieservant Resident>: Logging out
04:57:33 [INFO] - <mooncookieservant Resident>: Caps system for Bon Temps (35.91.208.199:13015) is aborting
04:57:33 [INFO] - <mooncookieservant Resident>: NetworkManager shutdown initiated
04:57:33 [DEBUG] - Marking end of execution run, deleting file: C:\Users\***\AppData\Roaming\Radegast\crash_marker
04:57:33 [INFO] - Texture pipeline shutting down
04:57:34 [INFO] - <mooncookieservant Resident>: NetworkManager shutdown initiated
04:57:34 [ERROR] - <mooncookieservant Resident>: Unhandled thread exception: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei OpenMetaverse.NetworkManager.Shutdown(DisconnectType type, String message)
   bei OpenMetaverse.NetworkManager.Shutdown(DisconnectType type)
   bei OpenMetaverse.NetworkManager.Logout()
   bei Radegast.frmMain.frmMain_FormClosing(Object sender, FormClosingEventArgs e) in C:\projects\radegast\Radegast\GUI\Dialogs\MainForm.cs:Zeile 394.
   bei System.Windows.Forms.Form.OnFormClosing(FormClosingEventArgs e)
   bei System.Windows.Forms.Form.WmClose(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

04:57:34 [DEBUG] - Marking end of execution run, deleting file: C:\Users\***\AppData\Roaming\Radegast\crash_marker
04:57:34 [INFO] - FMOD interface stopping
04:57:34 [DEBUG] - RadegastInstance finished cleaning up.

**Comment by JoranJix** [comment] 2023-01-28 04:04
Deleted my last comment. After removing all logs and any instance of radegast I had laying around on my PC I reinstalled it from the ground up with the latest version mentioned here. It seems to work fine now

**Comment by JoranJix** [comment] 2023-01-28 04:08
Until it stopped again... 

05:05] Teleporting home...
[05:05] Disconnected: SimShutdown (im standing on that sim. Its UP)


[Radegast.log](https://github.com/cinderblocks/radegast/files/10525268/Radegast.log)

**Comment by eauxnine** [comment] 2023-01-28 07:59
Here's my log. I also did a clean install and same issue. I just want to say thank you for so much for working on this! 
[Radegast.log](https://github.com/cinderblocks/radegast/files/10526644/Radegast.log)

**Comment by cinderblocks** [comment] 2023-01-28 18:09
"SimShutdown" is misleading to non-developers. It's a state of activity in the viewer. I'm working under assumption that there is a race condition and the disconnect timer isn't being reset somewhere. I am not able to reproduce the issue, surprisingingly, but it likely comes down to network ping and timing.

**Comment by eauxnine** [comment] 2023-01-28 19:47
So does that mean the fix for the issue would have to be on our end or we’re simply unable to use the viewer?

**Comment by cinderblocks** [comment] 2023-01-28 20:48
It means I just have to fix it blindly, but I’ll get it.

**Comment by JoranJix** [comment] 2023-01-29 01:17
I tried it with and without Pi-Hole activated on my network. But since our country is still lacking decent connectivity to the world, compared to the rest of europe, the timeouts should not be to harsh. Im running pings to SL AWS servers from 35 up to 200. Its sad. Also other countries have even higher pings.

**Comment by cinderblocks** [comment] 2023-02-05 03:48
Fixed in v2.41

**Closed by cinderblocks** 2023-02-05 03:48 UTC

**Comment by Venus-Drake** [comment] 2023-05-16 12:35
v2.41 log on RLV teleporting:
**15:29:44 [INFO] - <IosifMihai Resident>: Successfully set appearance
15:30:17 [WARN] - <IosifMihai Resident>: Could not find region named isla coral
15:30:17 [INFO] - <IosifMihai Resident>: Requesting teleport to region handle 0
15:30:17 [DEBUG] - Playing sound at <-197.5,98.5,215.9> ID cb58f920-5b52-8a49-b81c-e532adbbe6f1
15:30:47 [WARN] - <IosifMihai Resident>: Could not find region named isla coral
15:30:47 [INFO] - <IosifMihai Resident>: Requesting teleport to region handle 0
15:31:17 [WARN] - <IosifMihai Resident>: Could not find region named isla coral
15:31:17 [INFO] - <IosifMihai Resident>: Requesting teleport to region handle 0
15:31:47 [WARN] - <IosifMihai Resident>: Could not find region named isla coral
15:31:47 [INFO] - <IosifMihai Resident>: Requesting teleport to region handle 0**

I guarantee the region exists and RLV teleporting on exact same command works like a charm on FS, for example.

**Comment by krzysiekzpyrogrodu** [comment] 2024-07-01 07:35
it seems that some teleporting isues still are present only sure and always working is tp request... and I have 24.1 program euther does not react to atempts to triger tp or idling in the proces and then disconects
